system:
  worker: 1
  logger:
    level: 'debug'
    format: 'json'
    output: 'stdout'

input:
  - kafka:
      brokers: ['kafka-log-project-0406.g.aivencloud.com:18606']
      version: '4.2.1'
      topics: ['logistics_data_gen']
      group_id: logflow-group3
      worker: 1
      auto_offset_earliest: true
      auto_commit_interval: 30 # 单位：秒
      decorate_events: true
      codec: 'json'
      messages_queue_length: 8
      client_id: logflow-client
      discard_on_error: false
      sasl_enabled: true
      sasl_mechanism: SCRAM-SHA-512
      sasl_username: ''
      sasl_password: ''
      tls_enabled: true
      tls_ca: 'ca.pem'

filter:
  - json:
      source: time_utc
  - filters:
      if: ['Exist(level)']
      modules:
        - strip:
            fields: ['level']
        - uppercase:
            fields: ['level']
        - drop:
            if: ['EQ(level, "DEBUG")']
  - date:
      location: 'Asia/Shanghai'
      source: time_utc
      formats: ['yyyy-MM-dd HH:mm:ss.SSS', 'UNIX', 'UNIX_MS']
      target: datatime
  - dateFormat:
      source: datatime
      location: 'Asia/Shanghai'
      format: 'yyyy.MM.dd'
      target: "@localtime"
      set_if_fail: '1970.01.01'
      set_if_nil: '1970.01.01'
  - lowercase:
      fields: ['[@metadata][kafka][topic]']

output:
  - console:
      codec: 'json'
